baseURL: /
languageCode: en-us
title: Mathatistics
theme: cactus-extra
copyright: Mathatistics
disqusShortname: therimalaya
pygmentsUseClasses: true
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Writings
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: About
      url: /about
      weight: 4
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  logo: "mathatistics.svg"
  highlightjsVersion: "9.12.0"
  highlightjsLang: ["r", "yaml"]
  highlightjsTheme: "tomorrow"
  mathjax: true
  colortheme: white
  comments:
    enabled: no
    engine: disqus
  dateFormat: 'Jan 2, 2006'
  description: |
    Mathatistics includes tips, tutorials, techniques and some articles 
    related to Statistics, Data Science, Programming, LaTeX and Web Development.
  googleAnalyticsAsync: yes
  mainSection: posts
  postsOnHomePage: 5
  projectsUrl: https://github.com/mathatistics
  rss: yes
  show_updated: no
  showAllPostsOnHomePage: no
  showProjectsList: no
  social:
    - link: https://github.com/therimalaya
      name: github
    - link: https://no.linkedin.com/in/therimalaya
      name: linkedin
    - link: raju.rimal@medisin.uio.no
      name: email
  tagsOverview: yes
