baseURL: /
publishDir: docs
languageCode: en-us
title: Mathatistics
theme:
  - cactus-extra
  - grid-gallery
  - moderncv
copyright: Mathatistics
disqusShortname: therimalaya
pygmentsUseClasses: true
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Writings
      url: /blog
      weight: 2
    - name: Blog
      url: "http://mathaw.cloudrimalaya.com"
      weight: 3
    - name: Photography
      url: /photography
      weight: 4
    - name: About me
      url: /about
      weight: 5
    - name: Resume
      url: /cv
      weight: 6
    # - name: Tags
    #   url: /tags
    #   weight: 7
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 1
params:
  logo: "mathatistics.svg"
  highlightjsVersion: "9.12.0"
  highlightjsLang: ["r", "yaml"]
  highlightjsTheme: "tomorrow"
  mathjax: true
  colortheme: white
  comments:
    enabled: no
    engine: disqus
  dateFormat: "Jan 2, 2006"
  description: |
    Mathatistics includes tips, tutorials, techniques and some articles 
    related to Epidemilogy, Survival Analysis, Multivariate Analysis, Statistics, 
    Data Science, Programming, LaTeX and Web Development.
  googleAnalyticsAsync: yes
  mainSection: writings
  postsOnHomePage: 3
  projectsUrl: https://github.com/mathatistics
  rss: yes
  toc: yes
  show_updated: no
  showAllPostsOnHomePage: no
  showProjectsList: yes
  social:
    - link: raju.rimal@medisin.uio.no
      name: email
    - link: https://mathatistics.com/index.xml
      name: rss
    - link: https://mathatistics.com
      name: homepage
    - link: https://scholar.google.com/citations?user=UWO8g74AAAAJ
      name: scholar
    - link: https://orcid.org/0000-0001-6097-0285
      name: orcid
    - link: https://twitter.com/mathatistics
      name: twitter
    - link: https://github.com/therimalaya
      name: github
    - link: https://no.linkedin.com/in/therimalaya
      name: linkedin
  tagsOverview: no

